### ISSUE TITLE
discuss: simplify function names?

### ISSUE THREAD

**Issue by stevevanhooser** [VH-Lab/NDR-matlab#24]
readchannels_epochsamples => readsamples
read_epochevents => readevents?

or just read('samples', ...)  read('events',...)

For discussion...

**Comment by stevevanhooser** [comment]
Look at all of the functions in ndr.reader

and see if there are simpler names

**Comment by Sophie-Greer** [comment]
Here are the new function names I propose: 

base:
- ndr_reader_base_obj --> base
- epochclock --> clock
- t0_t1 --> t0_t1_base
- getchannelsepoch --> channels_base
- readchannels_epochsamples --> readsamples_base
- readevents_epochsamples --> readsamples_base
- readevents_epochsamples_native --> readnative_samples_base
- samplerate --> samplerate_base
- mfdaq_channeltypes --> mfdaq_channels
- mfdaq_prefix can stay the same
- mfdaq_type can stay the same

ced_smr
- ced_smr --> ced_smr_new
- getchannelsepoch --> channels_cedsmr
- readchannels_epochsamples --> readsamples_ced
- t0_t1 --> t0_t1_ced
- readevents_epochsamples_native --> readnative_samples_ced
- samplerate --> samplerate_cedsmr
- cedsmrfile --> identify_smr
- cedsmrheader2reacherchanneltype --> intan_to_reader

intan_rhd
- intan_rhd_obj --> intan_new
- t0_t1 --> t0_t1_intan
- getchannelsepoch --> channels_intan
- readevents_epochsamples --> readsamples_intan
- samplerate --> samplerate_intan
- filenamefromepochfiles --> filename_intan
- mfdaqchanneltype2intanheadertype --> mfdaq_to_intan
- intanheadertype2mfdaqchanneltype --> intan_to_mfdaq
- mfdaqchanneltype2intanchanneltype --> mfdaq_to_intan_channels
- intanname2mfdaqname --> intan_to_mfdaq_channels
- mfdaqchanneltype2intanfreqheader --> header_freq

somecompany_someformat
- somecompany_someformat -->  new_generic_base

spikegadgets_rec
- spikegadgets_rec --> spike_new
- getchannelsepoch --> channels_spike
- samplerate --> samplerate_spike
- t0_t1 --> t0_t1_spike
- getepochprobemap --> probe
- readchannels_epochsamples --> readsamples_spike
- filenamefromepochfiles --> filename

**Comment by Sophie-Greer** [comment]
Ok, I've taken another look at this and here are the functions that should keep their names across all classes (thanks, Steve, for the help):
t0_t1 
getchannelsepoch 
readchannels_epochsamples
readevents_epochsamples 
readevents_epochsamples_native 
samplerate
filenamefromepochfiles

**Comment by stevevanhooser** [comment]
read(channelType, channelNames_Numbers, 't0', -Inf, 't1', Inf,'useTime',1 )
% 
%.  Step 1: decode the channel names and channel types
%.  Step 2: if it is something that needs to be read with readchannels_epochsamples, then it calls that 
%.              if it is something that needs to be read with readevents_epochsamples, then it calls that

I will write a function prototype, ask NDR developers to write the channel decoders for their own reader

**Comment by lakesare** [comment]
Method names have been pretty confusing for me too.
When I was implementing their Python analogues I initially renamed them to more understandable names (and then went back to NDR names for consistency).

E.g.:

```
ndr_reader_base_obj --> self // It can be short, people know what `self`/`obj` means when it goes as the first argument in a method
t0_t1 --> get_t0_t1_of_epoch()
getchannelsepoch --> get_channels_of_epoch()
readchannels_epochsamples --> read_samples()
readevents_epochsamples --> read_events()
samplerate --> get_sample_rate()
```

`daqchannels2internalchannels` was also confusing, it's not immediately clear what's a daq channel name and what's an internal channel name, especially since some readers don't directly follow the distinction. `convert_channels_from_device_to_ndr_format()`?

I would probably also rename some arguments:

```
channelnumber --> channels // And require it to consistently be a cell array?
epochfiles --> files // Sometimes there is more than one epoch in a file
```

Not urgent, just a couple of thoughts.
