### ISSUE TITLE
Better docs: readchannels_epochsamples

### ISSUE THREAD

**Issue by stevevanhooser** [VH-Lab/NDR-matlab#25]
Should include the channel types that are allowed in the documentation, and an example

**Comment by stevevanhooser** [comment]
We need some text that describes how to specify an epoch, in terms of epochstreams and epoch_select

(epochstreams is a cell array of full path file names or remote access streams that comprise the epoch of data}
{epoch_select allows one to choose which epoch in the file one wants to access if the file or streams have more than one epoch contained in them. For most devices, epoch_select is always 1.)

Examples: If you had a file example.smr, then your epochstreams would be {'example.smr'} and epoch_select would be 1.

(Should go in ndr.reader documentation for readchannels_epochsamples)

**Comment by yijias-65** [comment]
%  READEVENTS_EPOCHSAMPLES - read events, markers, and digital events of specified channels for a specified epoch
			%
			%  [DATA] = READEVENTS_EPOCHSAMPLES(NDR_READER_BASE_OBJ, CHANNELTYPE, CHANNEL, EPOCHSTREAMS, EPOCH_SELECT, T0, T1)
			%
			%  CHANNELTYPE is the type of channel to read
			%  ('event','marker', 'dep', 'dimp', 'dimn', etc). It must be a a cell array of strings.
			%
			%  CHANNEL is a vector with the identity of the channel(s) to be read.
            %
			%   T0, T1 are beginning (t0) and end (t1) times to read
            %
            % EPOCHSTREAMS is a cell array of full path file names or remote 
            % access streams that comprise the epoch of data
            %
            % EPOCH_SELECT allows one to choose which epoch in the file one wants to access 
            % if the file or streams have more than one epoch contained in 
            % them. For most devices, epoch_select is always 1
            %
            % Examples: If you had a file example.smr, then your epochstreams 
            % would be {'example.smr'} and epoch_select would be 1
			%
			%  DATA is a two-column vector; the first column has the time of the event. The second
			%  column indicates the marker code. In the case of 'events,' this is just 1. If more than one channel
			%  is requested, DATA is returned as a cell array, one entry per channel.
