### ISSUE TITLE
need spikegadgets_rec read test function

### ISSUE THREAD

**Issue by stevevanhooser** [VH-Lab/NDR-matlab#47]
PLease make a test function analogous to 

ndr.test.reader.ced_smr.readertest

for spikegadgets

Thanks!
Steve

**Comment by stevevanhooser** [comment]
I made a new branch 'sophie_summer_3' for this and other issues

**Comment by stevevanhooser** [comment]
Hi @Sophie-Greer 

I don't see this file on the branch:

ndr.test.reader.spikegadgets.readertest

Is it maybe not pushed?

Thanks
Steve

**Comment by Sophie-Greer** [comment]
Hi Steve, 

It is here: ndr.reader.spikegadgets_rec.m. I also just made a new file called readertest in ndr.test.reader.spikegadgets.

**Comment by stevevanhooser** [comment]
Hi Sophie -

The readertest is supposed to test the functionality of the spikegadgets object using the 'read' method of the ndr.reader class.

The readertest document you made had the whole class. The spikegadgets_rec class is already defined in ndr.reader.spikegadgets_rec, so it was an error to define it again somewhere else. I removed the rest of the class redefinition and left just the test function as readertest.

I added a '.m' so it can be recognized by Matlab.

The readertest.m as provided is just a copy of ndr.test.reader.spikegadgets_rec.test, which tests the ability of the spikegadgets class to read through the 'readepoch_samples' functions, but it does not test the ability of the class to handle properly when called with the simpler 'read' function.

An example of a test file that uses the read function is ndr.test.reader.ced_smr.readertest.m. Can you imitate that file in ndr.test.reader.spikegadgets_rec.readertest.m?


I've pushed my changes to the ndr.test.reader.spikegadgets_rec.readertest.m file that essentially make it a copy of ndr.test.reader.spikegadgets_rec.test but it needs to be an imitation of ndr.test.reader.ced_smr.readertest.m.

Thanks
Steve

**Comment by Sophie-Greer** [comment]
Can we go over this today? Thanks.
