### ISSUE TITLE
edit beginnings of file ced_smr_channels.md to describe how to read CED SMR channels

### ISSUE THREAD

**Issue by stevevanhooser** [VH-Lab/NDR-matlab#49]
This file is at

https://github.com/VH-Lab/NDR-matlab/blob/sophie_summer_3/docs/notes/ced_smr_channels.md

or docs/notes/ced_smr_channels.md on disk

You can download a markdown reader extension for Chrome to be able to read the file on your own computer before you commit it and push it up to GitHub

**Comment by stevevanhooser** [comment]
I haven't managed to look through all the issues yet, but where it says "fill in", those are supposed to be filled in. For example, in the market row, it is specified by "mk" followed by the channel number, and an example would be "mk30" (marker on channel 30)

**Comment by Sophie-Greer** [comment]
Hi Steve, 

I edited what I could on docs.notes.ced_smr_channels.md and I hope we can go over the rest tomorrow.
