### ISSUE TITLE
add test of reading events, text, marker items to ndr.test.reader.ced_smr.readertest.m

### ISSUE THREAD

**Issue by stevevanhooser** [VH-Lab/NDR-matlab#51]

**Comment by stevevanhooser** [comment]
Created a new branch sophie_summer_4 for that purpose:

https://github.com/VH-Lab/NDR-matlab/tree/sophie_summer_4

Steve

**Comment by Sophie-Greer** [comment]
Hi Steve, 

I completed this task as best as I could. I hope you like my work!
